### ISSUE TITLE
GTEST_SKIP doesn't work in test environments

### ISSUE THREAD

**Issue by asomers** [google/googletest#2189]
GTEST_SKIP() works great when used in fixtures.  But it doesn't seem to have any effect when used in a test environment.  I would expect that every test case in the program gets skipped if an environment calls GTEST_SKIP().

Example program:
```c++
#include "gtest/gtest.h"

using ::testing::Test;

class SkipEnvironment : public testing::Environment {
 public:
  void SetUp() override {
    GTEST_SKIP() << "Skipping the entire environment";
  }
};

TEST(SkipTest, ShouldBeSkippedByEnvironment) {
  EXPECT_EQ(0, 1);
}

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);

  SkipEnvironment* const env = new SkipEnvironment;
  testing::AddGlobalTestEnvironment(env);

  return (RUN_ALL_TESTS());
```
Actual output:
```
Executing tests from //googletest/test:gtest_skip_environment_test
-----------------------------------------------------------------------------
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SkipTest
[ RUN      ] SkipTest.ShouldBeSkippedByEnvironment
googletest/test/gtest_skip_environment_test.cc:16: Failure
Expected equality of these values:
  0
  1
[  FAILED  ] SkipTest.ShouldBeSkippedByEnvironment (0 ms)
[----------] 1 test from SkipTest (0 ms total)
  
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SkipTest.ShouldBeSkippedByEnvironment

 1 FAILED TEST
```

cc @ngie-eign

**Comment by ngie-eign** [comment]
This seems like a subset of the issue I reported in #2169.

**Comment by ngie-eign** [comment]
Ok, interesting note. If we used GTEST_FAIL, it would bail out here. Let's give this a shot...

```
$ ./setup_environment_fatal_fail_demo 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
setup_environment_fatal_fail_demo.cc:8: Failure
Failed
Calling a fatal failure
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 0 tests, listed below:

 0 FAILED TESTS
```
Oh wow, that is confusing! Yup... that issue looks like #2169.

**Comment by ngie-eign** [comment]
Good news is, now it stops when GTEST_SKIP is triggered! Bad news is, the results are confusing as hell :P!
```
$ ./googlemock/gtest/gtest_skip_in_environment_setup_test 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
Should omit a skip message below
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
```

**Comment by ngie-eign** [comment]
> Good news is, now it stops when GTEST_SKIP is triggered! Bad news is, the results are confusing as hell :P!

...

I fixed the fact that it wasn't dumping out diagnostic information in #2203.

@EricWF, @gennadiycivil: please review the change.

**Comment by ngie-eign** [comment]
@asomers: this can be closed.

**Comment by forthright48** [comment]
@asomers and @ngie-eign : Why was this bug closed? It hasn't been merged to master yet right? I am still facing the same issue: GTEST_SKIP not working in test environments.

**Comment by asomers** [comment]
Yes it has been merged.  See PR #2203 .
