### ISSUE TITLE
Add CMake aliases

### ISSUE THREAD

**Issue by lukasm91** [google/googletest#2429]
GTest exports the following targets:
- `GTest::gtest`
- `GTest::gtest_main`
- `GTest::gmock`
- `GTest::gmock_main`

This targets should also be available when adding gtest with `add_subdirectory` (or `FetchContent`), because this should behave the same way as adding GTest with `find_package`. So somewhere, we should add the aliases to these targets, i.e.
```
add_library(GTest::gtest ALIAS gtest)
add_library(GTest::gtest_main ALIAS gtest_main)
add_library(GTest::gmock ALIAS gmock)
add_library(GTest::gmock_main ALIAS gmock_main)
```
I am not sure, where I should add these aliases.

**Comment by gennadiycivil** [comment]
Anything related to CMake is community supported. We do not use it internally and we are not in position to check. In general the maintainers would look for community consensus.

**Comment by Mizux** [comment]
My 2 cents,
for *gtest* and *gtest_main*:
First this CMake install **NAMESPACE** is defined here:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/CMakeLists.txt#L98
then used here:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/CMakeLists.txt#L105

libraries are defined later using a custom function cxx_library:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/CMakeLists.txt#L128-L129

note: gmock install rules seems to use an other macro/function:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googlemock/CMakeLists.txt#L121
defined  here (EDIT: just adding targets to the googletest target): https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/cmake/internal_utils.cmake#L327
(ed notice the of variable *${targets_export_name}*)

so we should try to add the `add_library(... ALIAS ...)` to the function:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/cmake/internal_utils.cmake#L147-L150
called by:
https://github.com/google/googletest/blob/306f3754a71d6d1ac644681d3544d06744914228/googletest/cmake/internal_utils.cmake#L197-L203

using the variable *${cmake_package_name}* which should be defined somewhere else IMHO...

**Comment by piotrzarycki** [comment]
can i take this?

**Comment by Mohammadmahdiamn** [comment]
Do whatever you think is best.

**Comment by AlexanderStein** [comment]
Is there any progress on this?

**Comment by hyukmyeong** [comment]
I think there is a pull request https://github.com/google/googletest/pull/3155 for the same issue

**Comment by Mizux** [comment]
@derekmauro  or @gennadiycivil please close this (since #3155 is merged).

ps: I don't have right to this repo to close it myself...

**Comment by kunjshukla** [comment]
hey, I would like to contribute to this issue. Please assign this to me.

**Comment by ED-1-0** [comment]
Is anyone working on this issue? This is my first time to contribute on open source project and I would like to work on this.

**Comment by LND694** [comment]
I think the issue is resolved.

**Comment by americadoodles** [comment]
I don't understand why this issue still not be closed. Github suggests this as a first good issue for the first contribution.

**Comment by lukasm91** [comment]
I would say this is fixed long time ago. https://github.com/google/googletest/pull/3155/files

As I created the issue 5 years ago, I'll probably just close it and let you open a new issue if you believe this is not resolved.
